apiVersion: v1
kind: ConfigMap
metadata:
  name: 'components-config'
  namespace: openshift-cluster-health-analyzer
data: 
  components.yaml: |
    components:
    - name: control-plane
      objects:
      - group: test-1
        resource: resource
      - group: test-2
      children:
      - name: cpu
        alerts:
          selectors:
          - matchLabels:
            - alertname: 
              - "KubeCPUOvercommit"
              - "HighOverallControlPlaneCPU"
      - name: B
        objects:
        - resource: nodes
      - name: etcd
        alerts:
          selectors:
          - matchLabels:
            - namespace:
              - openshift-etcd
              - openshift-etcd-operator
    - name: addons
      children:
      - name: kubevirt
        alerts:
          selectors:
          - matchLabels:
            - kubernetes_operator_part_of: 
              - kubevirt
          - matchLabels:
            - namespace: 
              - openshift-cnv
        objects:
        - group: kubevirt.io
          resource: kubevirts
binaryData: {}
immutable: false