apiVersion: v1
kind: ConfigMap
metadata:
  name: 'test-data'
  namespace: openshift-cluster-observability-operator
data: 
  incidents.yaml: |
    "THIS IS TESTING CONTENT"
binaryData: {}
immutable: false