apiVersion: v1
kind: ConfigMap
metadata:
  name: 'test-data'
  namespace: openshift-cluster-observability-operator
data: 
  incidents.yaml: |
    incidents:
      total: 2
      items:
      - id: 1
        severity: critical
        status: firing
        affectedComponents:
        - "etcd"
        - "kube-apiserver"
        alerts:
        - name: etcdHighNumberOfFailedProposals
          namespace: openshift-etcd
          severity": warning
          status: firing
          start_time: 2025-06-23T10:00:00Z
          end_time: null
binaryData: {}
immutable: false